# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: dettmering/hugo-build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk add --update nodejs npm
  - npm install -D postcss autoprefixer

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master
