# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: kdeleteme/hugo-sass-postcss

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - npm install --global autoprefixer

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master
