baseURL="https://kdeleteme.neocities.org"
languageCode="en-us"
title="kdeleteme's blog"
theme="kdeleteme"
copyright="- Copyright &#169; 2018-2019"

[params]
  author="kdeleteme"
  description="Rambling on free software, programming, and whatnot"
  gitlab_link="https://gitlab.com/kdeleteme/"

[taxonomies]
  tag="tags"
  category="categories"
