baseURL="kylobytes.neocities.org"
languageCode="en-us"
title="kylobytes"
theme="kylobytes"

[params]
  author="kdeleteme"
  description="Rambling on open source, programming, and whatever"
  gitlab_link="https://gitlab.com/kdeleteme/"

[taxonomies]
  tag="tags"
  category="categories"
