baseURL="https://kylobytes.neocities.org"
languageCode="en-us"
title="kylobytes"
theme="kylobytes"
copyright="- Copyright &#169; 2018-2019 - Kylobytes"

[params]
  author="kdeleteme"
  description="Rambling on open source, programming, and whatever"
  gitlab_link="https://gitlab.com/kdeleteme/"

[taxonomies]
  tag="tags"
  category="categories"
