baseURL="https://kdeleteme.neocities.org"
languageCode="en-us"
title="kdeleteme's blog"
theme="kdeleteme"
copyright="- Copyright &#169; 2018-2019 - kdeleteme"

[params]
  author="kdeleteme"
  description="Rambling on open source, programming, and whatever"
  gitlab_link="https://gitlab.com/kdeleteme/"

[taxonomies]
  tag="tags"
  category="categories"
