baseURL: "https://www.kylobytes.tech/"
languageCode: "en-us"
title: "kylobytes"
theme: "kylobytes"

params:
  author: "Kent Delante"    
  description: "My journey towards becoming a developer"
  gitlab_link: "https://gitlab.com/kdeleteme/"
  appsURL: "https://apps.kylobytes.tech"

taxonomies:
  tag: "tags"
  category: "categories"
