name: leftybournes-web
static_sites:
- build_command: npm install --global sass; rm -r ./public; hugo --destination ./public
  environment_slug: hugo
  envs:
    - key: HUGO_EXTENDED
      value: 1
  github:
    branch: main
    deploy_on_push: true
    repo: leftybournes/leftybournes-web
  name: leftybounes-web
